---
      #if vpc_id \ vpc_subnet_id  not defined, create a new one
vpc_cidr_block: 192.168.100.0/24
region: eu-central-1
vpc_name: testvpcname
hostpath: "/home/ubuntu/ansible/hosts"
output: "/home/ubuntu/ansible/output_log.yml"

    #create security group\s if not defined

    #create key_pair if not defined

    #variables  for instance deployment


      #  
      #         Deployment EC2 instance on AWS, required parameters in variables
      #         the values might be changed for particular VMs as well

instance_type: t2.micro 
image_id: ami-06ce824c157700cd2
keypair: ExchPair
security_group: sg-034bceb76fae44ec5
vpc_subnet_id: subnet-01bad4acbbef2bd1f

#       optional parameters:
#
# assign_public_ip: true
# tags:
#   name: instancename
#   service: webservice
# count: 3  #number of VMs of this type


    #[TBD] VM specify VM instance settings as objects in config file to deploy from 1 config file 

# vms:

#   - instance_type: t2.micro
#     image_id: "{{ image_id }}"
#     count: 2 #the number of instances with these params.
#     assign_public_ip: true
#     security_group: "{{ security_group }}"
#     vpc_subnet_id: "{{ vpc_subnet_id }}"
#     key_name: "{{ keypair }}"
#     tags:
#       Name: Webservice
#   - name: "vm2_viaans"
#     instance_type: t2.micro
#     vpc_subnet_id: "{{ vpc_subnet_id }}"
#     image_id: "{{ image_id }}"
#     security_group: "{{ security_group }}"
#     key_name: "{{ keypair }}"
